// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nifrnbzdjizwmbgatyfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pZnJuYnpkaml6d21iZ2F0eWZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzNzgzNDIsImV4cCI6MjA1Mzk1NDM0Mn0.yLXtcehUVPTcikW7oH5hToCy9Z6k9N-KN48krUi9a6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);